Create task15
Денис, объясните, пожалуйста, почему GitHub иногда отказывается загружать новый файл. Две задачи я загрузил, а на третьей получил сообщение: 
To https://github.com/velesslavVMS/vms2.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/velesslavVMS/vms2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Тогда я сначала загрузил 15 задачу, но название файла получилось Program.cs Тогда я создал новый файл с именем Tak15 и в него вставил созданный код. Как было правильно сделать?